POST http://localhost:3333/videos
Content-type: application/json


{
  "title" :"Video node aa",
  "description" :"Primeiro video",
  "duration" : 180
}

###


GET http://localhost:3333/videos

###


PUT http://localhost:3333/videos/fd3d8db9-cb2d-40af-8ea1-fbea5bf0b6d5
Content-Type: application/json

{
  "title" :"Video 023",
  "description" :"Primeiros video",
  "duration" : 180
}

###

DELETE http://localhost:3333/videos/062913e1-cd27-415c-b3f3-24c2e5cb7984


